In [2]:
import pandas as pd

In [6]:
df = pd.read_csv("final.csv", encoding="latin1")

In [8]:
df2= pd.read_stata('data/data_raw/GSDB_V4_dyadic.dta')

In [9]:
df2

,case_id,sanctioning_state_iso3,sanctioning_state,sanctioned_state_iso3,sanctioned_state,year,arms,military,trade,descr_trade,financial,travel,other,target_mult,sender_mult,objective,success
0,471,AFG,Afghanistan,AGO,Angola,1993-01-01,1,1,1,exp_part,0,0,0,0,1,end_war,success_total
1,471,AFG,Afghanistan,AGO,Angola,1994-01-01,1,1,1,exp_part,0,0,0,0,1,end_war,success_total
2,471,AFG,Afghanistan,AGO,Angola,1995-01-01,1,1,1,exp_part,0,0,0,0,1,end_war,success_total
3,471,AFG,Afghanistan,AGO,Angola,1996-01-01,1,1,1,exp_part,0,0,0,0,1,end_war,success_total
4,"471,574",AFG,Afghanistan,AGO,Angola,1997-01-01,1,1,1,exp_part,0,1,1,0,1,"end_war,end_war","success_total,success_total"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159060,"1031,1047",ZWE,Zimbabwe,YEM,"Yemen, North",2019-01-01,1,1,0,,1,1,0,0,1,"end_war,terrorism,human_rights,end_war,terrori...","ongoing,ongoing,ongoing,ongoing,ongoing,ongoing"
159061,"1047,1031",ZWE,Zimbabwe,YEM,"Yemen, North",2020-01-01,1,1,0,,1,1,0,0,1,"end_war,terrorism,human_rights,end_war,terrori...","ongoing,ongoing,ongoing,ongoing,ongoing,ongoing"
159062,"1031,1047",ZWE,Zimbabwe,YEM,"Yemen, North",2021-01-01,1,1,0,,1,1,0,0,1,"end_war,terrorism,human_rights,end_war,terrori...","ongoing,ongoing,ongoing,ongoing,ongoing,ongoing"
159063,"1031,1047",ZWE,Zimbabwe,YEM,"Yemen, North",2022-01-01,1,1,0,,1,1,0,0,1,"end_war,terrorism,human_rights,end_war,terrori...","ongoing,ongoing,ongoing,ongoing,ongoing,ongoing"
159064,"1031,1047",ZWE,Zimbabwe,YEM,"Yemen, North",2023-01-01,1,1,0,,1,1,0,0,1,"end_war,terrorism,human_rights,end_war,terrori...","ongoing,ongoing,ongoing,ongoing,ongoing,ongoing"

In [11]:
df

,gwcode,gw_name,microstate,year,ucdpongoing_all,ucdponset_all,maxintensity_all,conflict_ids_all,ucdpongoing_intra,ucdponset_intra,...,euds,aeuds,polity2,v2x_polyarchy,mrgdppc,sd_mrgdppc,pwtrgdp,sd_pwtrgdp,pwtpop,sd_pwtpop
0,2,United States of America,0,1946,0.0,0.0,NaN,NaN,0.0,0.0,...,1.293985,0.486256,9.0,0.603,15916.605087,2494.189575,2.565007e+06,1.075414e+06,142.942214,9.874863
1,2,United States of America,0,1947,0.0,0.0,NaN,NaN,0.0,0.0,...,1.308359,0.500630,9.0,0.607,15691.605157,2443.671758,2.524909e+06,1.097010e+06,145.613447,10.302882
2,2,United States of America,0,1948,0.0,0.0,NaN,NaN,0.0,0.0,...,1.343539,0.535809,9.0,0.599,15634.165601,2397.095016,2.621770e+06,1.143350e+06,148.443589,10.571322
3,2,United States of America,0,1949,0.0,0.0,NaN,NaN,0.0,0.0,...,1.330836,0.523106,9.0,0.580,15774.791549,2415.503157,2.724009e+06,1.187962e+06,150.554205,10.712760
4,2,United States of America,0,1950,1.0,1.0,1.0,238,0.0,0.0,...,1.354015,0.546286,9.0,0.585,16610.071657,2605.983858,2.831568e+06,1.207133e+06,153.549515,10.469628
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12642,990,Samoa/Western Samoa,1,2021,0.0,0.0,NaN,NaN,0.0,0.0,...,1.327329,0.519600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12643,990,Samoa/Western Samoa,1,2022,0.0,0.0,NaN,NaN,0.0,0.0,...,1.008024,0.200294,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12644,990,Samoa/Western Samoa,1,2023,0.0,0.0,NaN,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12645,990,Samoa/Western Samoa,1,2024,0.0,0.0,NaN,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12646,990,Samoa/Western Samoa,1,2025,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN